### ISSUE TITLE
Return in the script

### ISSUE THREAD

**Issue by taba929** [gonzaloriosley/Merge-PDF-Business-Central#1]
Hi Gonzalo,
first of all congratulations for your job, it's really amazing. I have only  one question: why in the script.js you return [buf] and not simply buf? For my work I have to return another parameter trough a json object: if you use [buf] I can't do this, although if I modify the script and use buf, my problem is solved. But I want an explanation before touching the code. Thanks

**Comment by gonzaloriosley** [comment]
Hi @taba929 
According to Microsoft documentation, the return parameter must be an array. Actually, I remember facing this issue in the past in other projects and having to pass a array no matter what.

https://docs.microsoft.com/en-us/dynamics-nav/invokeextensibilitymethod-method

If you change it and it keeps working, go for it :) I don´t see the problem.

Good luck

**Comment by taba929** [comment]
Thankyou for the reply
